apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-consumption-g3
  labels:
    app: energy-consumption-g3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-consumption-g3
  template:
    metadata:
      labels:
        app: energy-consumption-g3
    spec:
      nodeSelector:
        placement: edge
        type: g3
      containers:
      - name: ecs
        image: serodioj/energy-consumption-service:latest
        ports:
        - containerPort: 8000
          hostPort: 8000
        env:
        - name: hardware_config
          value: "default"
      - name: proxy
        image: serodioj/ecs-proxy:python
        env:
        - name: PYTHON_COMP
          value: "matmul"
