apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-consumption-rasp3
  labels:
    app: energy-consumption-rasp3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-consumption-rasp3
  template:
    metadata:
      labels:
        app: energy-consumption-rasp3
    spec:
      nodeSelector:
        placement: edge
        type: rasp3b
      containers:
      - name: ecs
        image: serodioj/energy-consumption-service:latest
        ports:
        - containerPort: 8000
          hostPort: 8000
        env:
        - name: hardware_config
          value: "rasp3"
      - name: proxy
        image: serodioj/ecs-proxy:python
        env:
        - name: PYTHON_COMP
          value: "matmul"
